CREATE TABLE IF NOT EXISTS datasets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  dataset_type TEXT NOT NULL,
  status TEXT NOT NULL,
  created_by_user_id BIGINT NOT NULL REFERENCES users(id),
  created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  archived_at_utc TIMESTAMPTZ,
  UNIQUE (tenant_id, code)
);

CREATE TABLE IF NOT EXISTS dataset_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  dataset_id BIGINT NOT NULL REFERENCES datasets(id) ON DELETE RESTRICT,
  version_number INTEGER NOT NULL,
  storage_kind TEXT NOT NULL,
  storage_uri TEXT NOT NULL,
  schema_fingerprint TEXT,
  split_policy JSONB NOT NULL DEFAULT '{}'::jsonb,
  published_by_user_id BIGINT NOT NULL REFERENCES users(id),
  published_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (tenant_id, dataset_id, version_number)
);

CREATE TABLE IF NOT EXISTS dataset_ingestion_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  dataset_version_id BIGINT NOT NULL REFERENCES dataset_versions(id) ON DELETE CASCADE,
  ingestion_kind TEXT NOT NULL,
  payload JSONB NOT NULL,
  created_by_user_id BIGINT NOT NULL REFERENCES users(id),
  created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS model_definitions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  model_family TEXT NOT NULL,
  status TEXT NOT NULL,
  created_by_user_id BIGINT NOT NULL REFERENCES users(id),
  created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  archived_at_utc TIMESTAMPTZ,
  UNIQUE (tenant_id, code)
);

CREATE TABLE IF NOT EXISTS model_definition_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  model_definition_id BIGINT NOT NULL REFERENCES model_definitions(id) ON DELETE RESTRICT,
  version_number INTEGER NOT NULL,
  architecture_payload JSONB NOT NULL,
  training_payload JSONB NOT NULL,
  compliance_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_by_user_id BIGINT NOT NULL REFERENCES users(id),
  created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (tenant_id, model_definition_id, version_number)
);

CREATE TABLE IF NOT EXISTS runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  dataset_version_id BIGINT NOT NULL REFERENCES dataset_versions(id) ON DELETE RESTRICT,
  model_definition_version_id BIGINT NOT NULL REFERENCES model_definition_versions(id) ON DELETE RESTRICT,
  run_name TEXT NOT NULL,
  status TEXT NOT NULL,
  training_config_payload JSONB NOT NULL,
  created_by_user_id BIGINT NOT NULL REFERENCES users(id),
  created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  started_at_utc TIMESTAMPTZ,
  completed_at_utc TIMESTAMPTZ,
  failed_at_utc TIMESTAMPTZ,
  failure_reason TEXT,
  UNIQUE (tenant_id, run_name)
);

CREATE TABLE IF NOT EXISTS run_events (
  id BIGSERIAL PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  run_id BIGINT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
  seq_no BIGINT NOT NULL,
  level TEXT NOT NULL,
  event_type TEXT NOT NULL,
  message TEXT NOT NULL,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (tenant_id, run_id, seq_no)
);

CREATE TABLE IF NOT EXISTS run_metric_points (
  id BIGSERIAL PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  run_id BIGINT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
  epoch INTEGER NOT NULL,
  step INTEGER,
  split TEXT NOT NULL,
  metric_name TEXT NOT NULL,
  metric_value DOUBLE PRECISION NOT NULL,
  created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS run_artifacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  run_id BIGINT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
  artifact_kind TEXT NOT NULL,
  artifact_uri TEXT NOT NULL,
  artifact_hash TEXT,
  size_bytes BIGINT,
  created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS registry_models (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  model_family TEXT NOT NULL,
  created_by_user_id BIGINT NOT NULL REFERENCES users(id),
  created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  archived_at_utc TIMESTAMPTZ,
  UNIQUE (tenant_id, code)
);

CREATE TABLE IF NOT EXISTS registry_model_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  registry_model_id BIGINT NOT NULL REFERENCES registry_models(id) ON DELETE RESTRICT,
  version_number INTEGER NOT NULL,
  source_run_id BIGINT NOT NULL REFERENCES runs(id) ON DELETE RESTRICT,
  artifact_id BIGINT REFERENCES run_artifacts(id),
  quality_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  governance_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_by_user_id BIGINT NOT NULL REFERENCES users(id),
  created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (tenant_id, registry_model_id, version_number)
);

CREATE TABLE IF NOT EXISTS audit_events (
  id BIGSERIAL PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  user_id BIGINT REFERENCES users(id),
  action TEXT NOT NULL,
  resource_type TEXT NOT NULL,
  resource_id TEXT,
  outcome TEXT NOT NULL,
  details JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_datasets_tenant_project ON datasets(tenant_id, project_id) WHERE archived_at_utc IS NULL;
CREATE INDEX IF NOT EXISTS idx_dataset_versions_tenant_dataset ON dataset_versions(tenant_id, dataset_id);
CREATE INDEX IF NOT EXISTS idx_model_definitions_tenant_project ON model_definitions(tenant_id, project_id) WHERE archived_at_utc IS NULL;
CREATE INDEX IF NOT EXISTS idx_runs_tenant_project_status ON runs(tenant_id, project_id, status);
CREATE INDEX IF NOT EXISTS idx_run_events_tenant_run ON run_events(tenant_id, run_id, seq_no);
CREATE INDEX IF NOT EXISTS idx_run_metrics_tenant_run_epoch ON run_metric_points(tenant_id, run_id, epoch);
CREATE INDEX IF NOT EXISTS idx_registry_versions_tenant_model ON registry_model_versions(tenant_id, registry_model_id);
CREATE INDEX IF NOT EXISTS idx_audit_events_tenant_time ON audit_events(tenant_id, created_at_utc DESC);

